// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1XYBeGrawKlixV6wLTb3Q4RZvjIjrIU',
    appId: '1:780660379860:web:4e29a3cee94e624ae36b41',
    messagingSenderId: '780660379860',
    projectId: 'nntu-app',
    authDomain: 'nntu-app.firebaseapp.com',
    storageBucket: 'nntu-app.appspot.com',
    measurementId: 'G-GPCDYLC25P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYGzc3RPlVLDWuMO929H9D0Ju1ReXfhPA',
    appId: '1:780660379860:android:711cb5825882b2e9e36b41',
    messagingSenderId: '780660379860',
    projectId: 'nntu-app',
    storageBucket: 'nntu-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-i6myld4WWajeWLUD0Xt793ZAmQ898DU',
    appId: '1:780660379860:ios:c937487cf0d64063e36b41',
    messagingSenderId: '780660379860',
    projectId: 'nntu-app',
    storageBucket: 'nntu-app.appspot.com',
    iosClientId: '780660379860-geque2mdg9qq425q6g4610q9vhv9t8rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.nntuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-i6myld4WWajeWLUD0Xt793ZAmQ898DU',
    appId: '1:780660379860:ios:c937487cf0d64063e36b41',
    messagingSenderId: '780660379860',
    projectId: 'nntu-app',
    storageBucket: 'nntu-app.appspot.com',
    iosClientId: '780660379860-geque2mdg9qq425q6g4610q9vhv9t8rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.nntuApp',
  );
}
